---
- name: json read age
  hosts: localhost
  vars:
    jsondata: "{{ lookup('file', 'age.json') | from_json }}"
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        var: jsondata
