---
- hosts: localhost
  tasks:
   - name: Register JSON output as a variable
     ansible.builtin.shell: cat domain_definition.json
     register: result
 
   - name: Set a variable
     ansible.builtin.debug:
       var: "{{ result.stdout | from_json }}"

   - name: Display all cluster names
     ansible.builtin.debug:
       var: item
     loop: "{{ domain_definition | community.general.json_query('domain.cluster[*].name') }}"


