---
- name: json read value
  hosts: localhost
  tasks:
    - name: Register JSON output as a variable
      ansible.builtin.shell: cat variable.json
      register: result

    - name: Set a variable
      ansible.builtin.set_fact:
        var: "{{ result.stdout | from_json }}"
    - name: Print variable
      ansible.builtin.debug:
        var: result